### ISSUE TITLE
Cargo.lock 

### ISSUE THREAD

**Issue by 0323pin** [Simhyeon/ced#2]
Hi,

Could we have the `Cargo.lock` file available in the repository, _I.e._ not hidden in `.gitignore`?
It would help me signicantly reduce the manual burden when updating the NetBSD package. We have a script that reads `Cargo.lock` and automatically generates a crate depends list. Having it available makes it much easier, right now I have to generate it locally and use a bunch of `sed` calls to convert it into the needed format.

TIA,
pin

**Comment by Simhyeon** [comment]
I excluded ```Cargo.lock``` from .gitignore on the latest commit. 

I made ced to be used as both library and binary which had cargo to automatically include cargo.lock in .gitignore file with ```--lib``` flag. I  hardly participated in any package distribution process so I have to admit that I have been careless about source code manipulation. It's a shame that you had to go through all those unnecessary procedures, my bad. 

Please let me know if you need other changes, I'll happily help. :)

**Comment by 0323pin** [comment]
@Simhyeon No worries, you couldn't possibly know this. Thanks for including it now 👍 

As `ced` doesn't have that many dependencies, it's not that bad to do it manually. But, when a project has over a hundred dependency crates, it becomes annoying.

Once again, thanks! Closing this issue now. I'll create a PR soon to add install instructions for NetBSD, if you don't mind.
